repos:
  #  - repo: https://github.com/psf/black
  #    rev: "19.3b0"
  #    hooks:
  #      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        exclude: '^.*\.(json|d\.ts)$'
